controller:
  control_limits:
    max:
    - 10000
    - 150
    min:
    - -10000
    - -150
  enable_trajectory_velocity_tracking: 0
  gamma: 1.0
  is_anti_windup: 0
  known_load: 1
  radial_params:
    alpha: 0.9
    eta: 500
    n_centers: 30
    variance: 0.1
  recalculation_threshold: 0.02
  rope_acceleration_limit: 9.81
  use_derivative: 0
  use_integral: 0
  use_neural_network: 0
  use_radial: 0
  weights:
    change_in_control:
    - 0
    - 0
    control:
    - 1
    - 1
    derivative:
    - 1000
    - 0.1
    integral:
    - 40.70327514
    - 0
    state:
    - 800000000
    - 10000000
    - 1300
    - 1300000
    - 2000000
    - 100000
    - 32400
    - 32400
crane_system:
  constraints:
    apply_optimization_constraints: 1
    apply_physical_constraints: 0
    rope:
      max: 1.01
      min: 0.1
    trolley:
      max: 2.05
      min: -0.1
  initial_conditions:
    hook_angle: 0.0
    load_angle: 0.0
    rope_length: 0.2
    trolley_position: 0.0
  physical_params:
    damping:
      hook: 0.06
      load: 0.06
      rope: 6.5
      trolley: 0.3
    friction:
      epsx: 0.01
      fr0x: 4.4
      krx: -0.5
    gravity: 9.81
    hook_to_load_distance: 0.2
    masses:
      hook: 2.0
      load: !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args:
        - f8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        AAAAAAAAGEA=
      trolley: 10.0
  target_positions:
    rope: 1
    target_tolerance: 0.01
    trolley: 2.0
genetic_algorithm:
  fitness_function:
    weights:
      w1: 15
      w2: 3
      w3: 0
      w4: 600
      w5: 5
      w6: 5
      w7: 1
  mutation:
    keep_parents: 1
    probability: 0.3
  num_generations: 1000
  num_genes: 10
  num_parents_mating: 4
  sol_per_pop: 12
  solution_space:
    I_range:
      high: 10000
      low: 0.0001
    Q_range:
      high: 10000000000000
      low: 0.0001
    R_range:
      high: 100000000
      low: 1.0e-07
logging:
  log_file: optimization_log.txt
  log_level: INFO
saving:
  plot_progress: true
  save_best_solution: true
simulation:
  controller_type: LQR
  duration: 20.0
  integration_method: rk4
  method: iterative
  print_detailed_data: true
  time_step: 0.01
trajectory:
  epsilon: 3
  k_a: 0.5
  k_v: 0.9
  t_x: 2.0
visualizer:
  all_plots_one_window: 0
  limits:
    x: 5
    y: 5
  render: false
  save_plots: false
